#!/usr/bin/env python3
"""
Build board-filtered index artifacts for product consumption.

Outputs to dist/:
  nodes-by-board.json    — three pre-filtered lists (cie, edx, both)
                           so products can load only what they need
  question-id-map.json   — canonical question-ID prefix per kn_id,
                           e.g. kn_0042 → {"cie": "cie.1.4", "edx": "edx.ch1-u7"}
                           used by Practice URL routing + exam numbering
  board-stats.json       — per-board counts by domain for KnowledgeMap tabs

These are derived artifacts — regenerated by build-all.py. Do not hand-edit.
"""

import json, os
from collections import defaultdict

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path):
    with open(os.path.join(BASE, path)) as f:
        return json.load(f)


def build_nodes_by_board(meta_nodes):
    """Split nodes into three lists based on primaryBoard.

    'both' nodes appear in both 'cie' and 'edx' result lists so that
    each board view is self-contained.
    """
    result = {'cie': [], 'edx': [], 'both': []}
    for mn in meta_nodes:
        board = mn.get('primaryBoard', 'cie')
        entry = {
            'kn_id': mn['kn_id'],
            'title_en': mn['title_en'],
            'title_zh': mn['title_zh'],
            'domain': mn['domain'],
            'subdomain': mn['subdomain'],
            'difficultyRange': mn['learning']['difficultyRange'],
        }
        result[board].append(entry)

    # Flattened views for product consumption
    flat = {
        'cie_view': [e for e in result['cie']] + [e for e in result['both']],
        'edx_view': [e for e in result['edx']] + [e for e in result['both']],
        'cie_only': result['cie'],
        'edx_only': result['edx'],
        'both': result['both'],
    }
    # Sort each list by kn_id for stable output
    for k in flat:
        flat[k].sort(key=lambda e: int(e['kn_id'].split('_')[1]))
    return flat


def build_question_id_map(meta_nodes, edx_map):
    """Generate canonical question-ID prefix for each node.

    Format:
      CIE:     cie.{section_without_s}   e.g. cie.1.4 for s1.4
      Edexcel: edx.{chapter}-{unit}      e.g. edx.ch1-u7
    """
    # Build reverse map: cie section → list of edx (ch, unit) pairs
    cie_to_edx = defaultdict(list)
    for ch_id, ch_data in edx_map.items():
        if not isinstance(ch_data, dict) or 'sections' not in ch_data:
            continue
        for unit_id, unit_data in ch_data['sections'].items():
            for cie_sec in unit_data.get('sections', []):
                cie_to_edx[f"s{cie_sec}"].append(unit_id)

    result = {}
    for mn in meta_nodes:
        kn_id = mn['kn_id']
        entry = {}
        cie = mn['examBoards'].get('cie_0580')
        edx = mn['examBoards'].get('edexcel_4ma1')

        if cie:
            sec = cie.get('section', '').lstrip('s')
            if sec:
                entry['cie'] = f"cie.{sec}"

        if edx:
            # For Edexcel-only nodes use their section directly
            # For both nodes, look up via CIE section
            edx_unit = None
            if cie:
                cie_sec = cie.get('section', '')
                units = cie_to_edx.get(cie_sec, [])
                if units:
                    edx_unit = units[0]
            if not edx_unit:
                # Fallback: use the edx section number
                sec = edx.get('section', '')
                if sec:
                    edx_unit = f"sec-{sec}"
            entry['edx'] = f"edx.{edx_unit}" if edx_unit else None

        if entry:
            result[kn_id] = entry

    return result


def build_board_stats(meta_nodes):
    """Per-board counts broken down by domain for KnowledgeMap tab UI."""
    stats = {
        'cie':  {'total': 0, 'domains': defaultdict(int)},
        'edx':  {'total': 0, 'domains': defaultdict(int)},
        'both': {'total': 0, 'domains': defaultdict(int)},
    }
    for mn in meta_nodes:
        board = mn.get('primaryBoard', 'cie')
        domain = mn.get('domain', 'unknown')
        stats[board]['total'] += 1
        stats[board]['domains'][domain] += 1

    # Convert defaultdicts to regular dicts for JSON serialization
    return {
        k: {
            'total': v['total'],
            'domains': dict(v['domains']),
        }
        for k, v in stats.items()
    }


def main():
    print("=== Building Board Indexes ===\n")

    meta_nodes = load('dist/meta-nodes.json')
    edx_map = load('registry/edx-kn-map.json')

    dist_dir = os.path.join(BASE, 'dist')
    os.makedirs(dist_dir, exist_ok=True)

    # 1. nodes-by-board.json
    nodes_by_board = build_nodes_by_board(meta_nodes)
    with open(os.path.join(dist_dir, 'nodes-by-board.json'), 'w') as f:
        json.dump(nodes_by_board, f, indent=2, ensure_ascii=False)
    print(f"nodes-by-board.json:")
    print(f"  cie_view: {len(nodes_by_board['cie_view'])} (cie_only={len(nodes_by_board['cie_only'])} + both={len(nodes_by_board['both'])})")
    print(f"  edx_view: {len(nodes_by_board['edx_view'])} (edx_only={len(nodes_by_board['edx_only'])} + both={len(nodes_by_board['both'])})")

    # 2. question-id-map.json
    qid_map = build_question_id_map(meta_nodes, edx_map)
    with open(os.path.join(dist_dir, 'question-id-map.json'), 'w') as f:
        json.dump(qid_map, f, indent=2, ensure_ascii=False)
    with_cie = sum(1 for v in qid_map.values() if 'cie' in v)
    with_edx = sum(1 for v in qid_map.values() if 'edx' in v)
    print(f"\nquestion-id-map.json:")
    print(f"  nodes with mapping: {len(qid_map)}")
    print(f"  with CIE prefix: {with_cie}")
    print(f"  with Edx prefix: {with_edx}")

    # 3. board-stats.json
    stats = build_board_stats(meta_nodes)
    with open(os.path.join(dist_dir, 'board-stats.json'), 'w') as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)
    print(f"\nboard-stats.json:")
    for board, s in stats.items():
        print(f"  {board}: {s['total']} total")
        for domain, count in sorted(s['domains'].items()):
            print(f"    {domain}: {count}")

    # 4. sections-index.json — section → [kn_ids] for quick lookup
    sections = defaultdict(lambda: {'kn_ids': [], 'title': '', 'domain': ''})
    for mn in meta_nodes:
        cie = mn['examBoards'].get('cie_0580')
        if not cie:
            continue
        sec = cie.get('section', '')
        if not sec:
            continue
        sections[sec]['kn_ids'].append(mn['kn_id'])
        if not sections[sec]['title']:
            sections[sec]['title'] = mn['title_en']
            sections[sec]['domain'] = mn['domain']

    # Convert to sorted regular dict
    sections_out = {}
    for sec in sorted(sections.keys()):
        s = sections[sec]
        primary = [k for k in s['kn_ids']
                   if not next((m for m in meta_nodes if m['kn_id'] == k), {}).get('variantOf')]
        sections_out[sec] = {
            'title': s['title'],
            'domain': s['domain'],
            'kn_ids': sorted(s['kn_ids'], key=lambda x: int(x.split('_')[1])),
            'primary_count': len(primary),
            'total_count': len(s['kn_ids']),
        }

    with open(os.path.join(dist_dir, 'sections-index.json'), 'w') as f:
        json.dump(sections_out, f, indent=2, ensure_ascii=False)
    print(f"\nsections-index.json: {len(sections_out)} sections")

    print("\nOutput: dist/nodes-by-board.json, question-id-map.json, board-stats.json, sections-index.json")


if __name__ == '__main__':
    main()
